# .github/workflows/mergeUpstreamBranches.yml

name: sync::biketag-infra#production
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '* * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'biketagorg'
          git config --global user.email 'biketagorg@gmail.com'
          # git config --global push.default 'current'

          # "git checkout production" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/keneucker/biketag-infra.git
          git fetch upstream
          
          # sync all production servers
          git checkout --track origin/production--biketag-app-dev
          git checkout production--biketag-app-dev
          git merge --no-edit upstream/production--biketag-app-dev
          git push origin production--biketag-app-dev
          
          git checkout --track origin/production--biketag-website-server-1
          git checkout production--biketag-website-server-1
          git merge --no-edit upstream/production--biketag-website-server-1
          git push origin production--biketag-website-server-1
